### ISSUE TITLE
some little bug in codes

### ISSUE THREAD

**Issue by LukeYuan2010** [zhang-can/SVM_PCA_face_detection#1]
the codes can't work well on my  PC, I changed it somewhere。

example:
add time module ：import time
use time as module's function: time() -->>time.time()

codes below can work well:
PICTURE_PATH =  os.path.join(os.getcwd(), "dataset/AR/")
file_name = PICTURE_PATH + "AR" + str(label).zfill(3) + "-" + str(sub_label) + ".tif"

may you enjon my suggestion!

呵呵！

**Comment by zhang-can** [comment]
@RootYuan Thanks for your suggestions! I tried again on my PC just now, and it works well.

For the 1st bug, I had imported the time module on "main.py" line 9.
For the 2nd bug, I wonder if it's because your Python IDE is different from mine(I use Pycharm 2017.2.3), I add an IDE suggestion on README.md.

Whatever, thanks a lot^_^
